name: RankHelper
main: com.mutinycraft.jigsaw.RankHelper.RankHelper
version: 0.1
author: Jigsaw
description: Simple plugin for changing the group of a player.

commands:
   rank:
      description: Changes the group of the given player.
      usage: /rank (player) (rank/group) [world]
   rankoffline:
      description: Changes the group of the given player regardless of their online status.
      usage: /rank (player) (rank/group) [world]
   rankinfo:
      description: Returns the group/s of a player in the provided world.
      usage: /rankinfo (player) (world)
   rankhelper:
      description: Displays help or reloads plugin
      usage: /bpermsrank [reload]